// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJXuOfuUYi4KzCm1RF2Ux61urJq8YDX4',
    appId: '1:557949024135:web:22f15975f3e1aa2fab0522',
    messagingSenderId: '557949024135',
    projectId: 'todo-c2331',
    authDomain: 'todo-c2331.firebaseapp.com',
    storageBucket: 'todo-c2331.appspot.com',
    measurementId: 'G-0HB9S5C8C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivhc_WGBqY1nhIYEcO-VG2XhSPcMtzsM',
    appId: '1:557949024135:android:45b16d0f3bd2d002ab0522',
    messagingSenderId: '557949024135',
    projectId: 'todo-c2331',
    storageBucket: 'todo-c2331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnrXIoKxVosShj8kaB_i3yO5O1po5UJHY',
    appId: '1:557949024135:ios:de8f65d18a20fadbab0522',
    messagingSenderId: '557949024135',
    projectId: 'todo-c2331',
    storageBucket: 'todo-c2331.appspot.com',
    iosClientId: '557949024135-ddm5id0k5s7vl72j8m5b8rur850v5phh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnrXIoKxVosShj8kaB_i3yO5O1po5UJHY',
    appId: '1:557949024135:ios:de8f65d18a20fadbab0522',
    messagingSenderId: '557949024135',
    projectId: 'todo-c2331',
    storageBucket: 'todo-c2331.appspot.com',
    iosClientId: '557949024135-ddm5id0k5s7vl72j8m5b8rur850v5phh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
